# Generated by Django 5.2.15 on 2026-07-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_siteimage_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentzone',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='contentzone',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='contentzone',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Bölüm adı'),
        ),
        migrations.AddField(
            model_name='contentzone',
            name='name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Bölüm adı'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='alt_text_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Görsel alt metni (SEO)'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='alt_text_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Görsel alt metni (SEO)'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='description_en',
            field=models.TextField(blank=True, help_text='Scroll-draw alt metni.', null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='description_tr',
            field=models.TextField(blank=True, help_text='Scroll-draw alt metni.', null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Hero slayt üst satırı.', max_length=200, null=True, verbose_name='Alt başlık'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='subtitle_tr',
            field=models.CharField(blank=True, help_text='Hero slayt üst satırı.', max_length=200, null=True, verbose_name='Alt başlık'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='title_tr',
            field=models.CharField(max_length=120, null=True, verbose_name='Başlık'),
        ),
    ]
