# Generated by Django 5.2.15 on 2026-07-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentzone_description_en_and_more'),
        ('localization', '0002_seed_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentZoneTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Bölüm adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_zone_translations', to='localization.language', verbose_name='Dil')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.contentzone', verbose_name='Bölge')),
            ],
            options={
                'verbose_name': 'İçerik bölgesi çevirisi',
                'verbose_name_plural': 'İçerik bölgesi çevirileri',
                'db_table': 'core_contentzone_translation',
                'constraints': [models.UniqueConstraint(fields=('zone', 'language'), name='unique_content_zone_translation_per_language')],
            },
        ),
        migrations.CreateModel(
            name='SiteImageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Başlık')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Alt başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt metin')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_image_translations', to='localization.language', verbose_name='Dil')),
                ('site_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.siteimage', verbose_name='Görsel')),
            ],
            options={
                'verbose_name': 'Site görseli çevirisi',
                'verbose_name_plural': 'Site görseli çevirileri',
                'db_table': 'core_siteimage_translation',
                'constraints': [models.UniqueConstraint(fields=('site_image', 'language'), name='unique_site_image_translation_per_language')],
            },
        ),
    ]
