# Generated by Django 6.0.6 on 2026-07-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP adresi')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Ülke')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='Ülke kodu')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Bölge / il')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Posta kodu')),
                ('location_address', models.TextField(blank=True, help_text='IP coğrafi konumundan üretilen okunabilir adres özeti.', verbose_name='Konum adresi')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('timezone', models.CharField(blank=True, max_length=64, verbose_name='Saat dilimi')),
                ('isp', models.CharField(blank=True, max_length=255, verbose_name='İnternet servis sağlayıcı')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='Host')),
                ('path', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Sayfa yolu')),
                ('full_url', models.URLField(blank=True, max_length=2000, verbose_name='Tam URL')),
                ('referrer', models.URLField(blank=True, max_length=2000, verbose_name='Referrer')),
                ('http_method', models.CharField(default='GET', max_length=10, verbose_name='HTTP metodu')),
                ('accept_language', models.CharField(blank=True, max_length=255, verbose_name='Dil tercihi')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Masaüstü'), ('mobile', 'Mobil'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('other', 'Diğer')], db_index=True, max_length=20, verbose_name='Cihaz tipi')),
                ('device_brand', models.CharField(blank=True, max_length=64, verbose_name='Cihaz markası')),
                ('device_model', models.CharField(blank=True, max_length=128, verbose_name='Cihaz modeli')),
                ('browser', models.CharField(blank=True, max_length=64, verbose_name='Tarayıcı')),
                ('browser_version', models.CharField(blank=True, max_length=32, verbose_name='Tarayıcı sürümü')),
                ('os_name', models.CharField(blank=True, max_length=64, verbose_name='İşletim sistemi')),
                ('os_version', models.CharField(blank=True, max_length=32, verbose_name='OS sürümü')),
                ('is_bot', models.BooleanField(db_index=True, default=False, verbose_name='Bot')),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ekran genişliği')),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ekran yüksekliği')),
                ('viewport_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Viewport genişliği')),
                ('viewport_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Viewport yüksekliği')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Oturum anahtarı')),
                ('visitor_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Ziyaretçi anahtarı')),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ziyaret zamanı')),
            ],
            options={
                'verbose_name': 'Site ziyareti',
                'verbose_name_plural': 'Site ziyaretleri',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['-visited_at', 'country'], name='analytics_s_visited_149a35_idx'), models.Index(fields=['ip_address', '-visited_at'], name='analytics_s_ip_addr_f2b265_idx'), models.Index(fields=['city', '-visited_at'], name='analytics_s_city_ca2fb1_idx')],
            },
        ),
    ]
