# Generated by Django 6.0.6 on 2026-07-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='is_staff_session',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin panelde giriş yapmış staff kullanıcı; kimlik bilgisi saklanmaz.', verbose_name='Yetkili oturum'),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='visit_source',
            field=models.CharField(choices=[('public', 'Ön yüz'), ('admin', 'Admin panel')], db_index=True, default='public', max_length=20, verbose_name='Kaynak'),
        ),
    ]
