# Generated by Django 6.0.6 on 2026-07-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_sitevisit_is_staff_session_sitevisit_visit_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='staff_username',
            field=models.CharField(blank=True, db_index=True, help_text='Ziyaret anındaki kullanıcı adı (yalnızca staff; superuser kaydı tutulmaz).', max_length=150, verbose_name='Staff kullanıcı'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='is_staff_session',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin panelde giriş yapmış staff kullanıcı.', verbose_name='Yetkili oturum'),
        ),
    ]
