# Generated by Django 6.0.6 on 2026-07-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_sitevisit_staff_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='staff_user_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Staff kullanıcı ID'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='staff_username',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Staff kullanıcı'),
        ),
    ]
