# Generated by Django 5.2.15 on 2026-07-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='BCP47, örn: tr, en', max_length=16, unique=True, verbose_name='Kod')),
                ('name_native', models.CharField(max_length=64, verbose_name='Yerel ad')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='languages/flags/', verbose_name='Bayrak')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_default', models.BooleanField(default=False, help_text='Aynı anda yalnızca bir dil varsayılan olabilir.', verbose_name='Varsayılan')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Dil',
                'verbose_name_plural': 'Diller',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UiStringKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=190, unique=True)),
                ('help_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'UI metin anahtarı',
                'verbose_name_plural': 'UI metin anahtarları',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='UiString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Metin')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_strings', to='localization.language', verbose_name='Dil')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='localization.uistringkey', verbose_name='Anahtar')),
            ],
            options={
                'verbose_name': 'UI çevirisi',
                'verbose_name_plural': 'UI çevirileri',
                'constraints': [models.UniqueConstraint(fields=('language', 'key'), name='uniq_uistring_lang_key')],
            },
        ),
    ]
