# Generated by Django 5.0.6 on 2026-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Örn: 7/24, 15 dk, 5000+', max_length=40, verbose_name='Değer')),
                ('label', models.CharField(help_text='Örn: Kesintisiz Hizmet, Ortalama Varış', max_length=120, verbose_name='Etiket')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Vitrin istatistiği',
                'verbose_name_plural': 'Vitrin istatistikleri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
