# Generated by Django 5.0.6 on 2026-07-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Örn: 🚗, 🛟', max_length=16, verbose_name='İkon (emoji)')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Hizmet kartı',
                'verbose_name_plural': 'Hizmet kartları',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Neden Çekici Pro?', help_text='H2 üstündeki küçük amber etiket.', max_length=120, verbose_name='Üst etiket')),
                ('title', models.CharField(default='Kapsamlı Yol Yardım Hizmetleri', max_length=200, verbose_name='Başlık (H2)')),
                ('description', models.TextField(blank=True, help_text='H2 altı paragraf. Yer tutucular: {business_name}, {region}', verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Hizmetler bölümü',
                'verbose_name_plural': 'Hizmetler bölümü',
            },
        ),
    ]
