# Generated by Django 5.2.15 on 2026-07-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_showcaseservice_showcaseservicesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseservice',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='showcaseservice',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='showcaseservice',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='showcaseservice',
            name='title_tr',
            field=models.CharField(max_length=120, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='showcaseservicesection',
            name='badge_en',
            field=models.CharField(default='Neden Çekici Pro?', help_text='H2 üstündeki küçük amber etiket.', max_length=120, null=True, verbose_name='Üst etiket'),
        ),
        migrations.AddField(
            model_name='showcaseservicesection',
            name='badge_tr',
            field=models.CharField(default='Neden Çekici Pro?', help_text='H2 üstündeki küçük amber etiket.', max_length=120, null=True, verbose_name='Üst etiket'),
        ),
        migrations.AddField(
            model_name='showcaseservicesection',
            name='description_en',
            field=models.TextField(blank=True, help_text='H2 altı paragraf. Yer tutucular: {business_name}, {region}', null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='showcaseservicesection',
            name='description_tr',
            field=models.TextField(blank=True, help_text='H2 altı paragraf. Yer tutucular: {business_name}, {region}', null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='showcaseservicesection',
            name='title_en',
            field=models.CharField(default='Kapsamlı Yol Yardım Hizmetleri', max_length=200, null=True, verbose_name='Başlık (H2)'),
        ),
        migrations.AddField(
            model_name='showcaseservicesection',
            name='title_tr',
            field=models.CharField(default='Kapsamlı Yol Yardım Hizmetleri', max_length=200, null=True, verbose_name='Başlık (H2)'),
        ),
        migrations.AddField(
            model_name='showcasestat',
            name='label_en',
            field=models.CharField(help_text='Örn: Kesintisiz Hizmet, Ortalama Varış', max_length=120, null=True, verbose_name='Etiket'),
        ),
        migrations.AddField(
            model_name='showcasestat',
            name='label_tr',
            field=models.CharField(help_text='Örn: Kesintisiz Hizmet, Ortalama Varış', max_length=120, null=True, verbose_name='Etiket'),
        ),
        migrations.AddField(
            model_name='showcasestat',
            name='value_en',
            field=models.CharField(help_text='Örn: 7/24, 15 dk, 5000+', max_length=40, null=True, verbose_name='Değer'),
        ),
        migrations.AddField(
            model_name='showcasestat',
            name='value_tr',
            field=models.CharField(help_text='Örn: 7/24, 15 dk, 5000+', max_length=40, null=True, verbose_name='Değer'),
        ),
    ]
