# Generated by Django 5.2.15 on 2026-07-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_seed_languages'),
        ('showcase', '0003_showcaseservice_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseServiceSectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, max_length=120, verbose_name='Üst etiket')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_section_translations', to='localization.language', verbose_name='Dil')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='showcase.showcaseservicesection', verbose_name='Hizmetler bölümü')),
            ],
            options={
                'verbose_name': 'Hizmetler bölümü çevirisi',
                'verbose_name_plural': 'Hizmetler bölümü çevirileri',
                'constraints': [models.UniqueConstraint(fields=('section', 'language'), name='unique_showcase_section_translation_per_language')],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_service_translations', to='localization.language', verbose_name='Dil')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='showcase.showcaseservice', verbose_name='Hizmet kartı')),
            ],
            options={
                'verbose_name': 'Hizmet kartı çevirisi',
                'verbose_name_plural': 'Hizmet kartı çevirileri',
                'constraints': [models.UniqueConstraint(fields=('service', 'language'), name='unique_showcase_service_translation_per_language')],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseStatTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=40, verbose_name='Değer')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Etiket')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_stat_translations', to='localization.language', verbose_name='Dil')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='showcase.showcasestat', verbose_name='İstatistik')),
            ],
            options={
                'verbose_name': 'Vitrin istatistiği çevirisi',
                'verbose_name_plural': 'Vitrin istatistiği çevirileri',
                'constraints': [models.UniqueConstraint(fields=('stat', 'language'), name='unique_showcase_stat_translation_per_language')],
            },
        ),
    ]
