# Generated by Django 5.0.6 on 2026-07-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'SSS',
                'verbose_name_plural': 'SSS',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=70, verbose_name='Sayfa başlığı (title)')),
                ('meta_description', models.CharField(max_length=160, verbose_name='Meta açıklama')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Anahtar kelimeler')),
                ('canonical_url', models.URLField(max_length=255, verbose_name='Canonical URL')),
                ('og_image_url', models.URLField(blank=True, max_length=500, verbose_name='OG görsel URL')),
                ('robots', models.CharField(default='index, follow', max_length=50, verbose_name='Robots')),
                ('business_name', models.CharField(max_length=100, verbose_name='İşletme adı')),
                ('legal_name', models.CharField(max_length=150, verbose_name='Yasal unvan')),
                ('tagline', models.CharField(max_length=120, verbose_name='Slogan')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('street', models.CharField(max_length=200, verbose_name='Adres (sokak)')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('region', models.CharField(max_length=100, verbose_name='Bölge')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Posta kodu')),
                ('country', models.CharField(default='TR', max_length=2, verbose_name='Ülke kodu')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Enlem')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Boylam')),
                ('opening_hours', models.CharField(default='Mo-Su 00:00-23:59', max_length=100, verbose_name='Çalışma saatleri (schema)')),
                ('price_range', models.CharField(default='₺₺', max_length=10, verbose_name='Fiyat aralığı')),
                ('area_served', models.JSONField(blank=True, default=list, verbose_name='Hizmet bölgeleri')),
                ('instagram_url', models.URLField(blank=True, max_length=255, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, max_length=255, verbose_name='Facebook')),
                ('site_url', models.URLField(max_length=255, verbose_name='Site URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
