# Generated by Django 5.0.6 on 2026-07-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default='© {year} {legal_name}. Tüm hakları saklıdır.', help_text='Alt bilgi satırı. Kullanılabilir: {year}, {legal_name}', max_length=255, verbose_name='Footer telif metni'),
        ),
    ]
