# Generated by Django 5.0.6 on 2026-07-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_footer_copyright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(help_text='Önerilen: 160 karakter altı. Maks. 320.', max_length=320, verbose_name='Meta açıklama'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Virgülle ayrılmış anahtar kelimeler. Maks. 500.', max_length=500, verbose_name='Anahtar kelimeler'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(help_text='Önerilen: 70 karakter altı (Google snippet). Maks. 120.', max_length=120, verbose_name='Sayfa başlığı (title)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='robots',
            field=models.CharField(default='index, follow', help_text='Örn: index, follow | noindex, nofollow | max-snippet:-1, max-image-preview:large', max_length=255, verbose_name='Robots'),
        ),
    ]
