# Generated by Django 5.0.6 on 2026-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_widen_seo_field_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='price_range',
            field=models.CharField(default='₺₺', help_text='Schema.org priceRange. Örn: ₺₺, ₺₺₺ veya kısa açıklama.', max_length=50, verbose_name='Fiyat aralığı'),
        ),
    ]
