# Generated by Django 5.0.6 on 2026-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_widen_price_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='Görsel URL')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Alt başlık')),
                ('alt_text', models.CharField(max_length=200, verbose_name='Görsel alt metni (SEO)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Hero Slayt',
                'verbose_name_plural': 'Hero Slaytları',
                'ordering': ['order', 'id'],
            },
        ),
    ]
