# Generated by Django 5.0.6 on 2026-07-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transfer_content_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Yüklü logo varsa navigatörde bu kullanılır.', upload_to='site_logo/%Y/%m/', verbose_name='Yüklenen logo'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Yüklü logo yoksa bu URL kullanılır.', max_length=500, verbose_name='Logo URL'),
        ),
    ]
