# Generated by Django 5.0.6 on 2026-07-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.FileField(blank=True, help_text='Tarayıcı sekmesi ikonu (.ico, .png, .svg). Yüklü dosya önceliklidir.', upload_to='site_favicon/%Y/%m/', verbose_name='Yüklenen favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='Yüklü favicon yoksa bu URL kullanılır.', max_length=500, verbose_name='Favicon URL'),
        ),
    ]
