# Generated by Django 5.0.6 on 2026-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_intro_badge',
            field=models.CharField(default='Aktif Hizmet', help_text='Başlık üstündeki küçük etiket.', max_length=80, verbose_name='Hero rozet metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_intro_body',
            field=models.TextField(blank=True, help_text='Sağ sütun paragrafları. Yer tutucular: {business_name}, {region}. CTA butonu şablonda sabittir.', verbose_name='Hero giriş metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_intro_title',
            field=models.TextField(blank=True, help_text='Ana başlık. Yer tutucular: {business_name}, {region}. Vurgulu gradient metin: {accent}Yol Yardım{/accent}', verbose_name='Hero başlık (H1)'),
        ),
    ]
