# Generated by Django 5.2.15 on 2026-07-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sitesettings_hero_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Cevap'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_tr',
            field=models.TextField(null=True, verbose_name='Cevap'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Soru'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='Soru'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='İşletme adı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='İşletme adı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='city_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='city_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='district_en',
            field=models.CharField(max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='district_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_en',
            field=models.CharField(default='© {year} {legal_name}. Tüm hakları saklıdır.', help_text='Alt bilgi satırı. Kullanılabilir: {year}, {legal_name}', max_length=255, null=True, verbose_name='Footer telif metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright_tr',
            field=models.CharField(default='© {year} {legal_name}. Tüm hakları saklıdır.', help_text='Alt bilgi satırı. Kullanılabilir: {year}, {legal_name}', max_length=255, null=True, verbose_name='Footer telif metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_intro_badge_en',
            field=models.CharField(default='Aktif Hizmet', help_text='Başlık üstündeki küçük etiket.', max_length=80, null=True, verbose_name='Hero rozet metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_intro_badge_tr',
            field=models.CharField(default='Aktif Hizmet', help_text='Başlık üstündeki küçük etiket.', max_length=80, null=True, verbose_name='Hero rozet metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_intro_body_en',
            field=models.TextField(blank=True, help_text='Sağ sütun paragrafları. Yer tutucular: {business_name}, {region}. CTA butonu şablonda sabittir.', null=True, verbose_name='Hero giriş metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_intro_body_tr',
            field=models.TextField(blank=True, help_text='Sağ sütun paragrafları. Yer tutucular: {business_name}, {region}. CTA butonu şablonda sabittir.', null=True, verbose_name='Hero giriş metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_intro_title_en',
            field=models.TextField(blank=True, help_text='Ana başlık. Yer tutucular: {business_name}, {region}. Vurgulu gradient metin: {accent}Yol Yardım{/accent}', null=True, verbose_name='Hero başlık (H1)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_intro_title_tr',
            field=models.TextField(blank=True, help_text='Ana başlık. Yer tutucular: {business_name}, {region}. Vurgulu gradient metin: {accent}Yol Yardım{/accent}', null=True, verbose_name='Hero başlık (H1)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Yasal unvan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_name_tr',
            field=models.CharField(max_length=150, null=True, verbose_name='Yasal unvan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.CharField(help_text='Önerilen: 160 karakter altı. Maks. 320.', max_length=320, null=True, verbose_name='Meta açıklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_tr',
            field=models.CharField(help_text='Önerilen: 160 karakter altı. Maks. 320.', max_length=320, null=True, verbose_name='Meta açıklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_en',
            field=models.CharField(blank=True, help_text='Virgülle ayrılmış anahtar kelimeler. Maks. 500.', max_length=500, null=True, verbose_name='Anahtar kelimeler'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords_tr',
            field=models.CharField(blank=True, help_text='Virgülle ayrılmış anahtar kelimeler. Maks. 500.', max_length=500, null=True, verbose_name='Anahtar kelimeler'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_en',
            field=models.CharField(help_text='Önerilen: 70 karakter altı (Google snippet). Maks. 120.', max_length=120, null=True, verbose_name='Sayfa başlığı (title)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_tr',
            field=models.CharField(help_text='Önerilen: 70 karakter altı (Google snippet). Maks. 120.', max_length=120, null=True, verbose_name='Sayfa başlığı (title)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='region_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Bölge'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='region_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Bölge'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='street_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Adres (sokak)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='street_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Adres (sokak)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Slogan'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_tr',
            field=models.CharField(max_length=120, null=True, verbose_name='Slogan'),
        ),
    ]
