# Generated by Django 5.2.15 on 2026-07-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_faq_answer_en_faq_answer_tr_faq_question_en_and_more'),
        ('localization', '0002_seed_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=300, verbose_name='Soru')),
                ('answer', models.TextField(blank=True, verbose_name='Cevap')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.faq', verbose_name='SSS')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_translations', to='localization.language', verbose_name='Dil')),
            ],
            options={
                'verbose_name': 'SSS çevirisi',
                'verbose_name_plural': 'SSS çevirileri',
                'constraints': [models.UniqueConstraint(fields=('faq', 'language'), name='unique_faq_translation_per_language')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=120, verbose_name='Sayfa başlığı')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='Meta açıklama')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Anahtar kelimeler')),
                ('business_name', models.CharField(blank=True, max_length=100, verbose_name='İşletme adı')),
                ('legal_name', models.CharField(blank=True, max_length=150, verbose_name='Yasal unvan')),
                ('tagline', models.CharField(blank=True, max_length=120, verbose_name='Slogan')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Adres (sokak)')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='İlçe')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Bölge')),
                ('footer_copyright', models.CharField(blank=True, max_length=255, verbose_name='Footer telif')),
                ('hero_intro_badge', models.CharField(blank=True, max_length=80, verbose_name='Hero rozet')),
                ('hero_intro_title', models.TextField(blank=True, verbose_name='Hero başlık')),
                ('hero_intro_body', models.TextField(blank=True, verbose_name='Hero giriş metni')),
                ('area_served', models.JSONField(blank=True, default=list, verbose_name='Hizmet bölgeleri')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_settings_translations', to='localization.language', verbose_name='Dil')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.sitesettings', verbose_name='Site ayarları')),
            ],
            options={
                'verbose_name': 'Site ayarı çevirisi',
                'verbose_name_plural': 'Site ayarı çevirileri',
                'constraints': [models.UniqueConstraint(fields=('settings', 'language'), name='unique_site_settings_translation_per_language')],
            },
        ),
    ]
