# Generated by Django 5.2.15 on 2026-07-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_modeltranslation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginDeviceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Cihaz anahtarı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Son IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Son User-Agent')),
                ('locked_until', models.DateTimeField(verbose_name='Kilit bitiş')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
            ],
            options={
                'verbose_name': 'Admin cihaz kilidi',
                'verbose_name_plural': 'Admin cihaz kilitleri',
                'ordering': ['-locked_until'],
            },
        ),
        migrations.CreateModel(
            name='AdminLoginSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_minutes', models.PositiveSmallIntegerField(default=5, help_text='Hatalı denemelerin sayıldığı süre.', verbose_name='Pencere süresi (dk)')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, help_text='Bu sayıya ulaşılınca ceza uygulanır.', verbose_name='Maks. hatalı deneme')),
                ('lockout_minutes', models.PositiveSmallIntegerField(default=5, help_text='Kilitlenme süresi.', verbose_name='Ceza süresi (dk)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
            ],
            options={
                'verbose_name': 'Admin giriş güvenlik ayarı',
                'verbose_name_plural': 'Admin giriş güvenlik ayarları',
            },
        ),
        migrations.CreateModel(
            name='AdminLoginUsernameLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Kullanıcı adı')),
                ('locked_until', models.DateTimeField(verbose_name='Kilit bitiş')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturuldu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
            ],
            options={
                'verbose_name': 'Admin kullanıcı adı kilidi',
                'verbose_name_plural': 'Admin kullanıcı adı kilitleri',
                'ordering': ['-locked_until'],
            },
        ),
        migrations.CreateModel(
            name='AdminLoginFailedAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='Kullanıcı adı')),
                ('device_key', models.CharField(db_index=True, max_length=64, verbose_name='Cihaz anahtarı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Admin hatalı giriş denemesi',
                'verbose_name_plural': 'Admin hatalı giriş denemeleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', '-created_at'], name='core_adminl_usernam_b00ec0_idx'), models.Index(fields=['device_key', '-created_at'], name='core_adminl_device__7c9c86_idx')],
            },
        ),
    ]
